name: Update Subtrees

on:
  schedule:
    # 매일 0시(UTC)에 실행 (한국 시각으로는 오전 9시)
    - cron: "0 0 * * *"
  # Actions 페이지에서 수동으로도 실행할 수 있도록 허용
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-subtrees:
    runs-on: ubuntu-latest

    steps:
      # 1) 메인 레포 체크아웃
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          # 서브트리에 푸시하려면 credentials가 필요
          persist-credentials: true

      # 2) Git 기본 설정
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      # 3) Subtree 업데이트
      - name: Pull from all subtrees
        run: |
          git subtree pull --prefix=진덕종 https://github.com/DeokJong/algorithm-study.git main --squash
          git subtree pull --prefix=윤경일 https://github.com/kidreamx/Algorithm_Coding main --squash

      # 4) 변경사항(커밋) 푸시
      - name: Push changes
        run: |
          # 충돌이 없다면 자동으로 병합 커밋(또는 스쿼시 커밋)이 생성된 상태일 것입니다.
          # 변경된 내용이 있으면 푸시.
          # 메인 레포에서 사용하는 브랜치가 main이라면:
          git push origin main
