name: Update Subtrees

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-subtrees:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
          ref: main

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Pull from all subtrees
        run: |
          git subtree pull --prefix=진덕종 https://github.com/DeokJong/algorithm-study.git main --squash -m "update: 진덕종 알고리즘 문제 풀이" || echo "No changes for 진덕종"
          git subtree pull --prefix=윤경일 https://github.com/kidreamx/Algorithm_Coding.git main --squash -m "update: 윤경일 알고리즘 문제 풀이" || echo "No changes for 윤경일"
          git subtree pull --prefix=심연수 https://github.com/Yeonsu-Sim/Algorithm.git main --squash -m "update: 심연수 알고리즘 문제 풀이" || echo "No changes for 심연수"
          git subtree pull --prefix=양정현 https://github.com/jhyang00815/algoguru.git main --squash -m "update: 양정현 알고리즘 문제 풀이" || echo "No changes for 양정현"

      - name: Push changes
        run: |
          # 변경된 내용 확인 및 커밋 후 푸시
          if git status --porcelain | grep .; then
            git add .
            git commit -m "chore: subtree updates"
            git push origin main
          else
            echo "No changes to commit"
          fi
